# Generated by Django 4.2.4 on 2023-09-27 22:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroCartao', models.CharField(max_length=20)),
                ('numeroBoleto', models.CharField(max_length=2000)),
                ('codigoPix', models.CharField(max_length=2000)),
                ('status', models.IntegerField(choices=[(1, 'Pendente'), (2, 'Aprovado'), (3, 'Recusado')], default=1)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Viagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorDiaria', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorasdjawdç', to='app.categorias')),
                ('fotos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fotos')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorFinal', models.DecimalField(decimal_places=1, max_digits=2)),
                ('animal', models.BooleanField(default=False)),
                ('nota', models.DecimalField(decimal_places=1, max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('pagamentoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentoId', to='app.pagamentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usurioReserva', to=settings.AUTH_USER_MODEL)),
                ('valorDiaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diariaViagem', to='app.viagens')),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagemReseva', to='app.viagens')),
            ],
        ),
    ]
