# Generated by Django 4.2.4 on 2023-09-27 22:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotos',
            name='link',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('dia', models.DateField(default=django.utils.timezone.now)),
                ('viagem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viagemAuxiliar', to='app.viagens')),
            ],
        ),
    ]
